package com.ludo.trailnav.watch;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.hardware.*;import android.location.*;import android.os.*;import com.ludo.trailnav.core.*;
public final class HikeService extends Service implements LocationListener,SensorEventListener{
 public static final String START="start",ARM="arm",STOP="stop";private static final int NOTIFICATION_ID=52;private android.content.SharedPreferences prefs;private LocationManager locations;private SensorManager sensors;private Sensor stepSensor;private Route route;private Route.Point directionAnchor;private long offCandidateSince=0,stationarySince=0;private final Handler pulseHandler=new Handler(Looper.getMainLooper());private final Runnable pulse=new Runnable(){public void run(){if(prefs==null||!prefs.getBoolean("armed",false)||prefs.getBoolean("active",false))return;long armedAt=prefs.getLong("armStartedWall",0);if(armedAt>0&&System.currentTimeMillis()-armedAt>=21600000L){prefs.edit().putBoolean("armed",false).putBoolean("at_start",false).apply();cancelContinuous();stopSelf();return;}requestSingleFix();pulseHandler.postDelayed(this,120000L);}};
 @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences("hike",0);locations=(LocationManager)getSystemService(LOCATION_SERVICE);sensors=(SensorManager)getSystemService(SENSOR_SERVICE);stepSensor=sensors.getDefaultSensor(Sensor.TYPE_STEP_COUNTER);}
 @Override public int onStartCommand(Intent i,int flags,int id){String a=i==null?null:i.getAction();if(STOP.equals(a)){stopHike();return START_NOT_STICKY;}try{route=RouteStore.load(this);}catch(Exception e){cancelAllLocation();stopSelf();return START_NOT_STICKY;}if(START.equals(a)){beginActive(false);return START_STICKY;}if(ARM.equals(a)){arm();return START_STICKY;}if(prefs.getBoolean("active",false)){pulseHandler.removeCallbacks(pulse);ensureForeground();registerSteps();requestContinuous();return START_STICKY;}if(prefs.getBoolean("armed",false)){cancelContinuous();pulseHandler.removeCallbacks(pulse);pulseHandler.post(pulse);return START_STICKY;}cancelAllLocation();stopSelf();return START_NOT_STICKY;}
 private void ensureForeground(){NotificationManager m=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);m.createNotificationChannel(new NotificationChannel("hiking","Hiking Trails",NotificationManager.IMPORTANCE_LOW));PendingIntent pi=PendingIntent.getActivity(this,30,new Intent(this,WatchActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification n=new Notification.Builder(this,"hiking").setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle("Hiking Trails").setContentText(route==null?"Offline trail":route.name).setContentIntent(pi).setOngoing(true).build();startForeground(NOTIFICATION_ID,n);}
 private void updateNotification(String s){NotificationManager m=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);PendingIntent pi=PendingIntent.getActivity(this,30,new Intent(this,WatchActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);try{m.notify(NOTIFICATION_ID,new Notification.Builder(this,"hiking").setSmallIcon(android.R.drawable.ic_menu_mylocation).setContentTitle("Hiking Trails").setContentText(s).setContentIntent(pi).setOngoing(true).build());}catch(Exception ignored){}}
 private void arm(){cancelContinuous();long now=System.currentTimeMillis();prefs.edit().putBoolean("armed",true).putBoolean("active",false).putBoolean("gps_valid",false).putBoolean("gps_weak",false).putBoolean("at_start",false).putBoolean("off_trail",false).putLong("armStartedWall",now).apply();updateNotification("Trail ready — arrival detection armed");pulseHandler.removeCallbacks(pulse);pulseHandler.post(pulse);}
 private void beginActive(boolean automatic){pulseHandler.removeCallbacks(pulse);cancelContinuous();ensureForeground();prefs.edit().putBoolean("active",true).putBoolean("armed",false).putBoolean("gps_valid",false).putBoolean("gps_weak",false).putBoolean("off_trail",false).putBoolean("finish_detected",false).putBoolean("finish_prompted",false).putBoolean("return_mode",false).putBoolean("reverse_prompt_pending",false).putBoolean("reverse_decided",false).putBoolean("reverse",false).putLong("startElapsed",SystemClock.elapsedRealtime()).putLong("startWall",System.currentTimeMillis()).putFloat("progress",0).putFloat("stepBaseline",-1).putInt("steps",0).apply();directionAnchor=null;offCandidateSince=0;registerSteps();requestContinuous();if(automatic)vibrate(180);updateNotification(automatic?"Hike started automatically":"Hike in progress");launchWatch();}
 private void requestContinuous(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{locations.requestLocationUpdates(LocationManager.GPS_PROVIDER,2000L,1f,this,Looper.getMainLooper());}catch(Exception ignored){}}
 private void cancelContinuous(){if(locations!=null)try{locations.removeUpdates(this);}catch(Exception ignored){}}
 private void cancelAllLocation(){pulseHandler.removeCallbacks(pulse);cancelContinuous();}
 private void requestSingleFix(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{locations.removeUpdates(this);locations.requestSingleUpdate(LocationManager.GPS_PROVIDER,this,Looper.getMainLooper());pulseHandler.postDelayed(()->{if(prefs.getBoolean("armed",false)&&!prefs.getBoolean("active",false))cancelContinuous();},15000L);}catch(Exception ignored){}}
 @Override public void onLocationChanged(Location l){if(route==null)return;Route.Point actual=new Route.Point(l.getLatitude(),l.getLongitude());long now=SystemClock.elapsedRealtime();prefs.edit().putFloat("lat",(float)l.getLatitude()).putFloat("lon",(float)l.getLongitude()).putFloat("accuracy",l.getAccuracy()).putLong("lastGpsElapsed",now).apply();if(prefs.getBoolean("armed",false)&&!prefs.getBoolean("active",false)){Route.Point s=route.points.get(0);double d=RouteMath.distance(actual,s);boolean at=d<=18&&l.getAccuracy()<=25;prefs.edit().putBoolean("at_start",at).apply();if(at){beginActive(true);}cancelContinuous();return;}if(!prefs.getBoolean("active",false))return;boolean good=l.hasAccuracy()&&l.getAccuracy()<=25;prefs.edit().putBoolean("gps_valid",good).putBoolean("gps_weak",!good).apply();if(!good)return;boolean reverse=prefs.getBoolean("reverse",false);float prior=prefs.getFloat("progress",0);RouteMath.Match match=nearestDirectional(actual,prior,reverse);if(match!=null){double off=match.offMeters;float next=(float)Math.max(prior,match.alongMeters);if(off<=35) prefs.edit().putFloat("progress",next).apply();if(off>28){if(offCandidateSince==0)offCandidateSince=now;if(now-offCandidateSince>8000&&!prefs.getBoolean("off_trail",false)){prefs.edit().putBoolean("off_trail",true).apply();vibrate(300);}}else{if(prefs.getBoolean("off_trail",false))vibrate(120);prefs.edit().putBoolean("off_trail",false).apply();offCandidateSince=0;}boolean atStart=RouteMath.distance(actual,reverse?route.points.get(route.points.size()-1):route.points.get(0))<=18;prefs.edit().putBoolean("at_start",atStart&&next<25).apply();if(next>route.meters*.90&&RouteMath.distance(actual,reverse?route.points.get(0):route.points.get(route.points.size()-1))<=22)prefs.edit().putBoolean("finish_detected",true).apply();detectReverse(actual,next);}}
 private RouteMath.Match nearestDirectional(Route.Point p,float prior,boolean reverse){if(!reverse)return RouteMath.nearest(route,p,prior,120);java.util.ArrayList<Route.Point> rev=new java.util.ArrayList<>(route.points);java.util.Collections.reverse(rev);return RouteMath.nearest(new Route(route.name,rev),p,prior,120);}
 private void detectReverse(Route.Point p,float prog){if(prog>80||prefs.getBoolean("reverse_decided",false))return;if(directionAnchor==null){directionAnchor=p;return;}if(RouteMath.distance(directionAnchor,p)<10)return;double move=RouteMath.bearing(directionAnchor,p),fwd=headingAt(20,false),rev=(fwd+180)%360;double df=Math.abs(delta(move,fwd)),dr=Math.abs(delta(move,rev));if(dr+25<df){prefs.edit().putBoolean("reverse_prompt_pending",true).apply();launchWatch();}directionAnchor=p;}
 private double headingAt(double meters,boolean reverse){Route.Point a=reverse?route.points.get(route.points.size()-1):route.points.get(0);double acc=0;Route.Point prev=a;if(!reverse){for(int i=1;i<route.points.size();i++){Route.Point q=route.points.get(i);acc+=RouteMath.distance(prev,q);if(acc>=meters)return RouteMath.bearing(a,q);prev=q;}}else{for(int i=route.points.size()-2;i>=0;i--){Route.Point q=route.points.get(i);acc+=RouteMath.distance(prev,q);if(acc>=meters)return RouteMath.bearing(a,q);prev=q;}}return 0;}
 private static double delta(double a,double b){double d=(b-a)%360;if(d>180)d-=360;if(d<-180)d+=360;return d;}
 private void registerSteps(){if(stepSensor!=null&&checkSelfPermission(Manifest.permission.ACTIVITY_RECOGNITION)==PackageManager.PERMISSION_GRANTED)sensors.registerListener(this,stepSensor,SensorManager.SENSOR_DELAY_NORMAL);}
 @Override public void onSensorChanged(SensorEvent e){if(e.sensor.getType()!=Sensor.TYPE_STEP_COUNTER)return;float base=prefs.getFloat("stepBaseline",-1);if(base<0){base=e.values[0];prefs.edit().putFloat("stepBaseline",base).apply();}prefs.edit().putInt("steps",Math.max(0,(int)(e.values[0]-base))).apply();}
 @Override public void onAccuracyChanged(Sensor s,int a){}
 private void vibrate(long ms){Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null)v.vibrate(VibrationEffect.createOneShot(ms,VibrationEffect.DEFAULT_AMPLITUDE));}
 private void launchWatch(){try{startActivity(new Intent(this,WatchActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP));}catch(Exception ignored){}}
 private void stopHike(){cancelAllLocation();if(sensors!=null)sensors.unregisterListener(this);prefs.edit().putBoolean("active",false).putBoolean("armed",false).putBoolean("gps_valid",false).putBoolean("gps_weak",false).putBoolean("off_trail",false).putBoolean("at_start",false).putBoolean("return_mode",false).putBoolean("finish_detected",false).putBoolean("reverse_prompt_pending",false).putLong("startElapsed",0).putLong("lastGpsElapsed",0).putFloat("progress",0).putFloat("stepBaseline",-1).putInt("steps",0).apply();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();}
 @Override public void onDestroy(){cancelAllLocation();if(sensors!=null)sensors.unregisterListener(this);super.onDestroy();}
 @Override public android.os.IBinder onBind(Intent i){return null;}
}
