package com.ludo.trailnav.watch;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.BitmapDrawable;import android.os.*;import android.view.*;import android.widget.FrameLayout;import androidx.wear.ambient.AmbientMode;import com.ludo.trailnav.core.*;import java.io.*;import java.util.*;
public final class WatchActivity extends Activity implements AmbientMode.AmbientCallbackProvider{
 private static final int REQ=271;private final Handler handler=new Handler(Looper.getMainLooper());private FrameLayout root;private TrailMapView map;private Route route;private long lastRev=-1;private boolean armAfterPermission=false,ambient=false;
 private final Runnable refresh=new Runnable(){public void run(){checkIncoming();if(map!=null)map.invalidate();checkPrompts();handler.postDelayed(this,1000);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setSystemUiVisibility(5894|1024|512);getWindow().setStatusBarColor(Color.BLACK);root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(6,17,12));setContentView(root);AmbientMode.attachAmbientSupport(this);checkIncoming();}
 @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);checkIncoming();}
 @Override protected void onResume(){super.onResume();if(!ambient)handler.post(refresh);}@Override protected void onPause(){handler.removeCallbacks(refresh);super.onPause();}
 @Override public AmbientMode.AmbientCallback getAmbientCallback(){return new AmbientMode.AmbientCallback(){@Override public void onEnterAmbient(Bundle d){ambient=true;handler.removeCallbacks(refresh);if(map!=null)map.setAmbient(true);}@Override public void onUpdateAmbient(){if(map!=null)map.invalidate();}@Override public void onExitAmbient(){ambient=false;if(map!=null)map.setAmbient(false);handler.removeCallbacks(refresh);handler.post(refresh);}};}
 private void checkIncoming(){long rev=getSharedPreferences("route",0).getLong("revision",0);if(rev!=lastRev||route==null){lastRev=rev;try{route=RouteStore.exists(this)?RouteStore.load(this):null;}catch(Exception e){route=null;}render();}boolean pending=getSharedPreferences("hike",0).getBoolean("start_pending",false)||getIntent().getBooleanExtra("start",false);if(pending&&route!=null){getSharedPreferences("hike",0).edit().putBoolean("start_pending",false).apply();getIntent().removeExtra("start");startHike();}}
 private void render(){root.removeAllViews();map=null;if(route==null){android.widget.TextView t=new android.widget.TextView(this);t.setText("NO TRAIL LOADED\n\nSend a GPX route from Hiking Trails on your phone.");t.setTextColor(Color.WHITE);t.setTextSize(17);t.setGravity(Gravity.CENTER);FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(-1,-1);p.setMargins(dp(30),dp(45),dp(30),dp(45));root.addView(t,p);return;}if(getSharedPreferences("hike",0).getBoolean("active",false))renderMap();else renderReady();}
 private void renderMap(){map=new TrailMapView(this,route);root.addView(map,new FrameLayout.LayoutParams(-1,-1));map.setActive(true);map.setAmbient(ambient);map.setSessionMenuAction(this::showSessionDialog);}
 private void renderReady(){root.addView(new ReadyScreenView(this),new FrameLayout.LayoutParams(-1,-1));}
 private int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private boolean havePermissions(){return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.ACTIVITY_RECOGNITION)==PackageManager.PERMISSION_GRANTED;}
 private void requestNeeded(){String[] p=Build.VERSION.SDK_INT>=33?new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACTIVITY_RECOGNITION,Manifest.permission.POST_NOTIFICATIONS}:new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACTIVITY_RECOGNITION};requestPermissions(p,REQ);}
 private void startHike(){if(route==null)return;armAfterPermission=false;if(!havePermissions()){requestNeeded();return;}startForegroundService(new Intent(this,HikeService.class).setAction(HikeService.START));renderMap();if(map!=null)map.followLocation();}
 private void armArrival(){if(route==null)return;armAfterPermission=true;if(!havePermissions()){requestNeeded();return;}armAfterPermission=false;startService(new Intent(this,HikeService.class).setAction(HikeService.ARM));}
 @Override public void onRequestPermissionsResult(int rq,String[] p,int[] g){super.onRequestPermissionsResult(rq,p,g);if(rq==REQ&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED){if(armAfterPermission){armAfterPermission=false;armArrival();}else startHike();}}
 private void checkPrompts(){android.content.SharedPreferences p=getSharedPreferences("hike",0);if(p.getBoolean("reverse_prompt_pending",false)){p.edit().putBoolean("reverse_prompt_pending",false).apply();new AlertDialog.Builder(this).setTitle("Trail direction").setMessage("It looks like you are following this trail in reverse.").setPositiveButton("FOLLOW IN REVERSE",(d,w)->{p.edit().putBoolean("reverse",true).putBoolean("reverse_decided",true).apply();if(map!=null)map.followLocation();}).setNegativeButton("KEEP FORWARD",(d,w)->p.edit().putBoolean("reverse_decided",true).apply()).show();}if(p.getBoolean("finish_detected",false)&&!p.getBoolean("finish_prompted",false)){p.edit().putBoolean("finish_prompted",true).apply();new AlertDialog.Builder(this).setTitle("Trail complete").setMessage("You reached the end of the saved route.").setPositiveButton("FINISH",(d,w)->finishHike()).setNegativeButton("KEEP HIKING",null).show();}}
 private void showSessionDialog(){if(!getSharedPreferences("hike",0).getBoolean("active",false))return;boolean ret=getSharedPreferences("hike",0).getBoolean("return_mode",false);new AlertDialog.Builder(this).setTitle("Hike session").setMessage(ret?"Return-to-start mode is active.":"Resume, return to the trailhead, or stop this hike?").setPositiveButton("STOP",(d,w)->finishHike()).setNegativeButton("RESUME",null).setNeutralButton(ret?"EXIT RETURN":"RETURN TO START",(d,w)->{getSharedPreferences("hike",0).edit().putBoolean("return_mode",!ret).apply();if(map!=null){map.followLocation();map.invalidate();}}).show();}
 private void finishHike(){if(route==null){reset();return;}android.content.SharedPreferences p=getSharedPreferences("hike",0);float prog=Math.max(0,p.getFloat("progress",0));int steps=Math.max(0,p.getInt("steps",0));long st=p.getLong("startElapsed",0),sec=st>0?Math.max(0,(SystemClock.elapsedRealtime()-st)/1000):0;int complete=route.meters<=0?0:(int)Math.min(100,Math.round(prog*100f/(float)route.meters));String entry=HikeHistory.record(this,route.name,prog,steps,sec,complete);HikeHistorySync.push(this,entry);reset();String sum=String.format(Locale.US,"%s\n%.2f mi • %,d steps • %02d:%02d:%02d • %d%%",route.name,prog/1609.344,steps,sec/3600,(sec/60)%60,sec%60,complete);new AlertDialog.Builder(this).setTitle("Hike ended").setMessage(sum+"\n\nKeep this trail ready, or clear it for your next park?").setPositiveButton("CLEAR TRAIL",(d,w)->clearTrail()).setNegativeButton("KEEP TRAIL",(d,w)->render()).show();}
 private void reset(){stopService(new Intent(this,HikeService.class));getSharedPreferences("hike",0).edit().clear().apply();}
 private void clearTrail(){reset();RouteStore.clear(this);File f=new File(getFilesDir(),"route_photo.jpg");if(f.exists())f.delete();getSharedPreferences("route",0).edit().remove("areaName").remove("photoCredit").apply();route=null;render();}
 private final class ReadyScreenView extends View{private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final Paint.FontMetrics fm=new Paint.FontMetrics();private Bitmap photo;private final RectF startHit=new RectF(),laterHit=new RectF();ReadyScreenView(Context c){super(c);setClickable(true);File f=new File(getFilesDir(),"route_photo.jpg");photo=f.isFile()?BitmapFactory.decodeFile(f.getAbsolutePath()):null;if(photo==null)try{photo=BitmapFactory.decodeStream(getAssets().open("chapel_branch_ready.jpg"));}catch(Exception ignored){}}
  @Override protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();if(w<=0||h<=0)return;drawCover(c,w,h);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(112,0,0,0));c.drawRect(0,0,w,h,p);String[] title=splitTwo(route.name.toUpperCase(Locale.US));float tsp=fit(title,w*.76f,17,11.5f);drawLines(c,title,w/2f,h*.205f,h*.285f,tsp,Color.WHITE,true);String area=getSharedPreferences("route",0).getString("areaName",route.name);String[] al=splitMaybe(area.toUpperCase(Locale.US),w*.70f,10.5f);float asp=fit(al,w*.70f,10.5f,7.5f);if(al.length==1)text(c,al[0],w/2f,h*.385f,asp,Color.rgb(235,242,237),true);else drawLines(c,al,w/2f,h*.365f,h*.405f,asp,Color.rgb(235,242,237),true);text(c,"READY • OFFLINE",w/2f,h*.495f,11,Color.rgb(113,242,168),true);float bw=w*.31f,bh=h*.096f,gap=w*.055f,cy=h*.64f,lx=w/2f-gap/2-bw/2,rx=w/2f+gap/2+bw/2;startHit.set(lx-bw/2,cy-bh/2,lx+bw/2,cy+bh/2);laterHit.set(rx-bw/2,cy-bh/2,rx+bw/2,cy+bh/2);action(c,startHit,"START",true);action(c,laterHit,"LATER",false);String credit=getSharedPreferences("route",0).getString("photoCredit","");if(!credit.isEmpty())text(c,credit,w/2f,h*.80f,6.7f,Color.argb(220,255,255,255),false);}
  private void drawCover(Canvas c,int w,int h){if(photo==null){c.drawColor(Color.rgb(8,29,18));return;}float s=Math.max(w/(float)photo.getWidth(),h/(float)photo.getHeight()),dx=(w-photo.getWidth()*s)/2,dy=(h-photo.getHeight()*s)/2;Matrix m=new Matrix();m.setScale(s,s);m.postTranslate(dx,dy);c.drawBitmap(photo,m,p);}
  private void action(Canvas c,RectF r,String label,boolean primary){p.setStyle(Paint.Style.FILL);p.setColor(primary?Color.rgb(55,231,136):Color.argb(205,20,55,38));float rad=r.height()/2;c.drawRoundRect(r,rad,rad,p);if(!primary){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(dp(1.5f));p.setColor(Color.WHITE);c.drawRoundRect(r,rad,rad,p);}text(c,label,r.centerX(),r.centerY(),11.8f,primary?Color.rgb(2,42,20):Color.WHITE,true);}
  private String[] splitTwo(String x){String[] w=x.trim().replaceAll("\\s+"," ").split(" ");if(w.length<2)return new String[]{x};p.setTextSize(sp(17));p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);int best=1;float score=Float.MAX_VALUE;for(int i=1;i<w.length;i++){String a=join(w,0,i),b=join(w,i,w.length);float sc=Math.max(p.measureText(a),p.measureText(b));if(sc<score){score=sc;best=i;}}return new String[]{join(w,0,best),join(w,best,w.length)};}
  private String[] splitMaybe(String x,float max,float s){p.setTextSize(sp(s));p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);if(p.measureText(x)<=max)return new String[]{x};return splitTwo(x);}private String join(String[] w,int a,int b){StringBuilder s=new StringBuilder();for(int i=a;i<b;i++){if(s.length()>0)s.append(' ');s.append(w[i]);}return s.toString();}
  private float fit(String[] l,float max,float start,float min){p.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);for(float s=start;s>=min;s-=.25f){p.setTextSize(sp(s));boolean ok=true;for(String q:l)if(p.measureText(q)>max)ok=false;if(ok)return s;}return min;}
  private void drawLines(Canvas c,String[] l,float x,float y1,float y2,float s,int col,boolean bold){if(l.length==1)text(c,l[0],x,(y1+y2)/2,s,col,bold);else{text(c,l[0],x,y1,s,col,bold);text(c,l[1],x,y2,s,col,bold);}}
  private void text(Canvas c,String t,float x,float cy,float s,int col,boolean bold){p.setStyle(Paint.Style.FILL);p.setColor(col);p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.DEFAULT);p.setTextSize(sp(s));p.setTextAlign(Paint.Align.CENTER);p.getFontMetrics(fm);c.drawText(t,x,cy-(fm.ascent+fm.descent)/2,p);}private float sp(float v){return v*getResources().getDisplayMetrics().scaledDensity;}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_UP){if(startHit.contains(e.getX(),e.getY())){performClick();startHike();return true;}if(laterHit.contains(e.getX(),e.getY())){performClick();armArrival();moveTaskToBack(true);return true;}}return true;}@Override public boolean performClick(){super.performClick();return true;}}
}
