package com.ludo.trailnav.phone;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import com.google.android.gms.wearable.*;import com.ludo.trailnav.core.*;import java.io.*;import java.util.*;
public final class PhoneActivity extends Activity{
 private static final int OPEN_GPX=89; private final int GREEN=Color.rgb(63,231,137),PALE=Color.rgb(225,244,232);private LinearLayout body;private TextView state,history;private Route current;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(6,16,12));getWindow().setNavigationBarColor(Color.rgb(6,16,12));ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(Color.rgb(6,16,12));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(24),dp(42),dp(24),dp(28));s.addView(body);setContentView(s);heading("HIKING TRAILS",28,GREEN);info("Import an exported AllTrails GPX track, then send it to your Galaxy Watch.");heading("Selected trail",16,PALE);state=label("Loading…",18,PALE);action("IMPORT GPX FROM ALLTRAILS",this::openGpx);action("SEND TO WATCH",()->transfer(false));action("SEND + START ON WATCH",()->transfer(true));heading("Offline navigation",17,GREEN);info("After transfer, the watch saves the GPX and navigates with its own GPS. No mobile signal or map tiles are required.");heading("Hike History",17,GREEN);history=label("No completed hikes yet.",14,Color.rgb(173,198,183));refresh();}
 @Override protected void onResume(){super.onResume();refreshHistory();}
 private int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private TextView label(String t,int sz,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sz);v.setTextColor(c);v.setPadding(0,dp(8),0,dp(8));body.addView(v);return v;}private void heading(String t,int s,int c){TextView v=label(t,s,c);v.setTypeface(android.graphics.Typeface.DEFAULT,1);}private void info(String t){TextView v=label(t,15,Color.rgb(173,198,183));v.setLineSpacing(dp(3),1f);}
 private void action(String t,Runnable r){TextView b=new TextView(this);b.setText(t);b.setTextColor(Color.rgb(0,30,14));b.setTextSize(14);b.setGravity(Gravity.CENTER);b.setTypeface(android.graphics.Typeface.DEFAULT,1);GradientDrawable g=new GradientDrawable();g.setColor(GREEN);g.setCornerRadius(dp(22));b.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(6),0,dp(8));body.addView(b,p);b.setOnClickListener(v->r.run());}
 private void refresh(){try{current=RouteStore.exists(this)?RouteStore.load(this):RouteStore.seedSample(this);state.setText(current.name+"\n"+String.format(Locale.US,"%.2f mi • %d route points",current.meters/1609.344,current.points.size()));}catch(Exception e){current=null;state.setText("No trail loaded. Tap Import GPX.");}refreshHistory();}
 private void refreshHistory(){if(history!=null){String h=getSharedPreferences("history",0).getString("entries","");history.setText(h.isEmpty()?"No completed hikes yet.":h);}}
 private void openGpx(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,OPEN_GPX);}
 @Override protected void onActivityResult(int rq,int rs,Intent d){super.onActivityResult(rq,rs,d);if(rq!=OPEN_GPX||rs!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();new Thread(()->{try(InputStream in=getContentResolver().openInputStream(u)){RouteStore.save(this,RouteStore.readAll(in));runOnUiThread(()->{refresh();toast("Trail imported");});}catch(Exception e){runOnUiThread(()->error("Import error: "+e.getMessage()));}}).start();}
 private String areaFor(Route r){if(r==null)return "";String n=r.name.toLowerCase(Locale.US);Route.Point p=r.points.get(0);if(n.contains("chapel branch")||Math.hypot(p.lat-38.63221,p.lon+75.63807)<.01)return "Chapel Branch Nature Area";return r.name;}
 private void transfer(boolean start){if(current==null){error("Import a GPX file first");return;}state.setText("Sending “"+current.name+"” to watch…");new Thread(()->{try{byte[] g=RouteStore.bytes(this);PutDataMapRequest req=PutDataMapRequest.create(TrailLink.ROUTE_PATH);req.getDataMap().putAsset(TrailLink.ROUTE_ASSET,Asset.createFromBytes(g));req.getDataMap().putBoolean(TrailLink.START_NOW,start);req.getDataMap().putLong(TrailLink.REVISION,System.currentTimeMillis());req.getDataMap().putString(TrailLink.AREA_NAME,areaFor(current));req.getDataMap().putString(TrailLink.PHOTO_CREDIT,"Photo: Delmarva Trails & Waterways");try(InputStream pi=getAssets().open("chapel_branch_ready.jpg")){req.getDataMap().putAsset(TrailLink.PHOTO_ASSET,Asset.createFromBytes(RouteStore.readAll(pi)));}catch(Exception ignored){}Wearable.getDataClient(this).putDataItem(req.asPutDataRequest().setUrgent()).getResult();runOnUiThread(()->{refresh();toast(start?"Sent + starting on watch":"Sent to watch");});}catch(Exception e){runOnUiThread(()->error("Send error: "+e.getMessage()));}}).start();}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void error(String s){new AlertDialog.Builder(this).setTitle("Hiking Trails").setMessage(s).setPositiveButton("OK",null).show();}
}
